apiVersion: v1
kind: Service
metadata:
  name: back-trans
  namespace: prod
spec:
  selector:
    app: back-trans
  ports:
    - name: http-8800
      port: 8800
      targetPort: 8800
  type: ClusterIP