name: Backtrans Build and Deploy on VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start ssh-agent and add private key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build Docker image using private base image
        run: |
          IMAGE_NAME=${{ secrets.VM_HOST }}:5000/back-trans:latest
          BASE_IMAGE=${{ secrets.VM_HOST }}:5000/golang:1.24-alpine

          echo "Building Docker image with base image: $BASE_IMAGE"

          sudo docker build \
            --build-arg BASE_IMAGE=$BASE_IMAGE \
            -t $IMAGE_NAME .

      - name: Transfer image to remote VM and load it
        run: |
          IMAGE_NAME=${{ secrets.VM_HOST }}:5000/back-trans:latest

          echo "Saving and loading image on remote VM..."

          sudo docker save $IMAGE_NAME | \
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "docker load"

      - name: Push image from remote VM to private registry
        run: |
          IMAGE_NAME=${{ secrets.VM_HOST }}:5000/back-trans:latest

          echo "Pushing image to private registry from remote VM..."

          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "docker push $IMAGE_NAME"
