name: Backtrans Build and Deploy on VM

on:
  push:
    branches:
      - main
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start ssh-agent and add private key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set image variables
        id: vars
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "IMAGE_NAME=${{ secrets.MY_DOMAIN }}/back-trans:latest" >> "$GITHUB_ENV"
            echo "BASE_IMAGE=${{ secrets.MY_DOMAIN }}/golang:1.24-alpine" >> "$GITHUB_ENV"
            echo "CONTAINER_NAME=back-trans" >> "$GITHUB_ENV"
            echo "HOST_PORT=8800" >> "$GITHUB_ENV"
            echo "CONTAINER_PORT=8800" >> "$GITHUB_ENV"
          else
            echo "IMAGE_NAME=${{ secrets.MY_DOMAIN }}/back-trans:test" >> "$GITHUB_ENV"
            echo "BASE_IMAGE=${{ secrets.MY_DOMAIN }}/golang:1.24-alpine" >> "$GITHUB_ENV"
            echo "CONTAINER_NAME=back-trans-test" >> "$GITHUB_ENV"
            echo "HOST_PORT=8801" >> "$GITHUB_ENV"
            echo "CONTAINER_PORT=8800" >> "$GITHUB_ENV"
          fi

      - name: Build Docker image using private base image
        run: |
          echo "Building Docker image with base image: $BASE_IMAGE"
          sudo docker build \
            --build-arg BASE_IMAGE=$BASE_IMAGE \
            -t $IMAGE_NAME .

      - name: Transfer image to remote VM and load it
        run: |
          echo "Saving and transferring image to remote VM..."
          sudo docker save $IMAGE_NAME | \
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "docker load"

      - name: Push image to private registry from remote VM
        run: |
          echo "Pushing image to private registry from remote VM..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "docker push $IMAGE_NAME"

      - name: Deploy container on remote VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "
            docker stop $CONTAINER_NAME || true && \
            docker rm $CONTAINER_NAME || true && \
            docker pull $IMAGE_NAME && \
            docker run -d --name $CONTAINER_NAME \
              -p $HOST_PORT:$CONTAINER_PORT \
              --restart always \
              -e MYSQL_USER='$MYSQL_USER' \
              -e MYSQL_PASS='$MYSQL_PASS' \
              -e MYSQL_HOST='$MYSQL_HOST' \
              -e MYSQL_PORT='$MYSQL_PORT' \
              -e MYSQL_DBNAME='$MYSQL_DBNAME' \
              -e REDIS_HOST='$REDIS_HOST' \
              -e REDIS_PORT='$REDIS_PORT' \
              -e REDIS_PASSWORD='$REDIS_PASSWORD' \
              $IMAGE_NAME
          "
