name: Back-trans CI/CD deploy to EC2 dev

on:
   push:
     branches:
       - backup-dev
   workflow_dispatch:

jobs:
  deploy:
    name: Deploy Back-trans to EC2
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Start SSH agent
      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_EXP_DEV_PRIVATE_KEY }}

      # 3️⃣ Set environment variables
      - name: Set environment variables
        run: |
          echo "BUILD_TARGET=back-trans" >> "$GITHUB_ENV"
          echo "IMAGE_NAME=back-trans-dev:latest" >> "$GITHUB_ENV"
          echo "CONTAINER_NAME=back-trans-dev" >> "$GITHUB_ENV"
          echo "CONTAINER_PORT=8800" >> "$GITHUB_ENV"
          echo "HOST_PORT=8741" >> "$GITHUB_ENV"
          echo "VM_USER=${{ secrets.VM_USER_DEV }}" >> "$GITHUB_ENV"
          echo "VM_HOST=${{ secrets.VM_HOST_DEV }}" >> "$GITHUB_ENV"

      # 4️⃣ Parse EC2 secrets JSON to env file
      - name: Parse back-trans EC2 secrets
        run: |
          echo '${{ secrets.EC2_DEV_BACK_TRANS_SECRETS }}' > back-trans.json
          jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' back-trans.json > back-trans.env
          shred -u back-trans.json

      # 5️⃣ Prepare APNs and FCM credential files
      - name: Prepare APNs and FCM files
        run: |
          echo '${{ secrets.APNS_P8_KEY_DEV }}' | sed 's/\\n/\n/g' | tr -d '\r' > apns.p8
          echo '${{ secrets.FCM_CREDENTIALS_JSON_DEV }}' > firebase.json

      # 5️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            --build-arg BUILD_TARGET=${BUILD_TARGET} \
            -t $IMAGE_NAME .

      #  6️⃣ Copy files to EC2
      - name: Copy secrets and credential files to EC2
        run: |
          scp -o StrictHostKeyChecking=no back-trans.env $VM_USER@$VM_HOST:/tmp/back-trans.env
          scp -o StrictHostKeyChecking=no apns.p8 $VM_USER@$VM_HOST:/tmp/apns.p8
          scp -o StrictHostKeyChecking=no firebase.json $VM_USER@$VM_HOST:/tmp/firebase.json
          shred -u apns.p8 firebase.json back-trans.env

      # 8️⃣ Deploy Docker container on EC2
      - name: Deploy back-trans on EC2
        run: |
          docker save $IMAGE_NAME | ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST "
            docker load && \
            docker stop $CONTAINER_NAME || true && \
            docker rm $CONTAINER_NAME || true && \
            docker run -d --name $CONTAINER_NAME \
              -p $HOST_PORT:$CONTAINER_PORT \
              --restart always \
              --network app_network \
              -v /tmp/apns.p8:/app/apns.p8:ro \
              -v /tmp/firebase.json:/app/firebase.json:ro \
              --env-file /tmp/back-trans.env \
              $IMAGE_NAME
          "

#
